// Sampling is deprecated in spec 2026-07-28 (SEP-2577) with a 12-month window; this file
// exists precisely to demonstrate it (MRTR-first, legacy fallback), so the diagnostic is
// suppressed here and nowhere else. Remove the tool or migrate when the window closes.
#pragma warning disable MCP9005

using System.ComponentModel;
using ModelContextProtocol;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace Gaia.Mcp.Server.Tools;

/// <summary>
/// Example tool demonstrating sampling: the server asks the connected MCP client's
/// own LLM to generate text. Supports both the 2026-07-28 MRTR flow (input_required /
/// retry-with-responses, works on stateless connections) and the legacy server-initiated
/// sampling/createMessage request for stateful down-level clients.
/// </summary>
[McpServerToolType]
public static class SamplingTools
{
    private const string SamplingRequestKey = "summarize_llm";

    [McpServerTool(Name = "sampling_summarize", ReadOnly = true, OpenWorld = false), Description(
        "Provides a one-sentence summary of the supplied text, generated by the CLIENT's own LLM via MCP sampling — the server itself has no model. " +
        "How to use: pass the text to summarize; on 2026-07-28 clients this round-trips via an input_required result (MRTR), on older stateful clients via a sampling/createMessage request — either way the client must support sampling. " +
        "Use to test or demonstrate client-side sampling support end to end. This is an example tool, used for systems testing.")]
    public static async Task<string> SummarizeAsync(
        McpServer server,
        RequestContext<CallToolRequestParams> context,
        [Description("The text to summarize. The client's LLM receives it with a one-sentence-summary instruction.")] string text,
        CancellationToken cancellationToken)
    {
        // MRTR retry leg: the client answered our sampling input request.
        if (context.Params?.InputResponses?.TryGetValue(SamplingRequestKey, out var response) is true)
        {
            var result = response.Deserialize(InputResponse.CreateMessageResultJsonTypeInfo);
            var summary = result?.Content.OfType<TextContentBlock>().FirstOrDefault()?.Text;
            return summary is null
                ? "Client answered the sampling request without text content."
                : $"Summary (via client LLM): {summary}";
        }

        // MRTR first leg: hand the LLM call to the client as an input request.
        if (server.IsMrtrSupported)
        {
            throw new InputRequiredException(
                inputRequests: new Dictionary<string, InputRequest>
                {
                    [SamplingRequestKey] = InputRequest.ForSampling(BuildSamplingRequest(text))
                },
                requestState: "awaiting-summary");
        }

        // Legacy path: server-initiated sampling/createMessage (deprecated in 2026-07-28,
        // still the only option for stateful pre-MRTR clients that advertise sampling).
        if (server.ClientCapabilities?.Sampling is not null)
        {
            var result = await server.SampleAsync(BuildSamplingRequest(text), cancellationToken);
            var summary = result.Content.OfType<TextContentBlock>().FirstOrDefault()?.Text;
            return summary is null
                ? "Client answered the sampling request without text content."
                : $"Summary (via client LLM): {summary}";
        }

        return "This client supports neither MRTR nor the sampling capability, so the server cannot borrow its LLM. " +
               "Connect with a client that registers a sampling handler to use this tool.";
    }

    private static CreateMessageRequestParams BuildSamplingRequest(string text) => new()
    {
        Messages =
        [
            new SamplingMessage
            {
                Role = Role.User,
                Content = [new TextContentBlock { Text = $"Summarize the following in one short sentence:\n\n{text}" }]
            }
        ],
        MaxTokens = 200
    };
}
